server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://pet-discovery-server.pg1.krane.9rum.cc:8761/eureka

---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://pet-discovery-server.pg1.krane.9rum.cc:8761/eureka